### GET request to home controller
GET http://localhost:9001/books

### GET request to home controller
GET http://localhost:9001/books/1234567892

### POST request to create a book
POST http://localhost:9001/books
Content-Type: application/json

{
  "author": "Lyra Silverstar",
  "title": "Northern Lights",
  "isbn": "1234567891",
  "price": 9.90
}

### POST bad request to create a book
POST http://localhost:9001/books
Content-Type: application/json

{
  "author": "Lyra Silverstar",
  "title": "",
  "isbn": "1234abc567891",
  "price": 9.90
}

### GET request to home controller
GET http://localhost:9001/

### POST refresh config
POST http://localhost:9001/actuator/refresh
